-- Seed RICE editorial works into the unified `works` table (program='rice').
-- Generated from apps/rice/assets/articles.json.

INSERT INTO works (project_slug, program_key, series_key, series_title, author, title, status, sort_order, notes, cover_image, popup_description, kind, place, keywords, disclosure, href, published_at) VALUES ('crowley-modernism', 'rice', 'seed', 'Seed', 'C. Sandbatch', 'Crowley Modernism', 'sample', 1000, 'ref: RCE-ESS-001', 'assets/images/feature/feature-essays.jpg', 'Rice, oil, levees, and a modernism assembled from pumps, invoices, and wet heat.', 'essay', 'Acadia Parish', '["rice", "oil", "levee", "modernism"]', 'Editorial sample; not part of a released issue.', 'crowley-modernism.html', NULL);
INSERT INTO works (project_slug, program_key, series_key, series_title, author, title, status, sort_order, notes, cover_image, popup_description, kind, place, keywords, disclosure, href, published_at) VALUES ('rice-rice-art-002', 'rice', 'seed', 'Seed', NULL, 'Against Cotton Memory', 'planned', 1001, NULL, NULL, 'A proposed refusal of the South as soft-focus inheritance and decorative ruin.', 'essay', 'Delta interior', '["cotton", "memory", "anti-pastoral"]', 'Planned work; not published.', NULL, NULL);
INSERT INTO works (project_slug, program_key, series_key, series_title, author, title, status, sort_order, notes, cover_image, popup_description, kind, place, keywords, disclosure, href, published_at) VALUES ('the-pump-house', 'rice', 'seed', 'Seed', 'L. Doucet', 'The Pump House', 'sample', 1002, 'ref: RCE-FIC-003', 'assets/images/feature/feature-fiction.jpg', 'A machine runs through the night while the water keeps its own account.', 'fiction', 'Vermilion Parish', '["machinery", "water", "night shift"]', 'Editorial sample; not part of a released issue.', 'the-pump-house.html', NULL);
INSERT INTO works (project_slug, program_key, series_key, series_title, author, title, status, sort_order, notes, cover_image, popup_description, kind, place, keywords, disclosure, href, published_at) VALUES ('rice-rice-fic-002', 'rice', 'seed', 'Seed', NULL, 'Twenty-Six Hours of Fluorescent Light', 'planned', 1003, NULL, NULL, 'A proposed story of a convenience store, tropical weather, and debt.', 'fiction', 'Jefferson Davis Parish', '["convenience store", "storm", "debt"]', 'Planned work; not published.', NULL, NULL);
INSERT INTO works (project_slug, program_key, series_key, series_title, author, title, status, sort_order, notes, cover_image, popup_description, kind, place, keywords, disclosure, href, published_at) VALUES ('crawfish-pond-with-saints', 'rice', 'seed', 'Seed', 'C. Sandbatch', 'Crawfish Pond with Saints', 'sample', 1004, 'ref: Folio 04', 'assets/images/feature/feature-poetry.jpg', 'Eight lines filed between a pump house, a trap line, and a hymn.', 'poetry', 'Gulf interior', '["wetland", "devotion", "agriculture"]', 'Editorial sample; not part of a released issue.', 'crawfish-pond-with-saints.html', NULL);
INSERT INTO works (project_slug, program_key, series_key, series_title, author, title, status, sort_order, notes, cover_image, popup_description, kind, place, keywords, disclosure, href, published_at) VALUES ('rice-rice-poe-002', 'rice', 'seed', 'Seed', NULL, 'Three Rice Songs', 'planned', 1005, NULL, NULL, 'A proposed sequence for water, machinery, and voices carried across a field.', 'poetry', 'Gulf interior', '["sequence", "water", "machinery"]', 'Planned work; not published.', NULL, NULL);
INSERT INTO works (project_slug, program_key, series_key, series_title, author, title, status, sort_order, notes, cover_image, popup_description, kind, place, keywords, disclosure, href, published_at) VALUES ('field-at-1942', 'rice', 'seed', 'Seed', 'RICE Editors', 'Field at 19:42', 'sample', 1006, 'ref: RICE-VR-FLD-001', 'assets/images/archive/new-orleans-street-field-note.jpg', 'A prototype field-note image testing place, caption, and evidence systems.', 'archive', 'New Orleans, Louisiana', '["field", "weather", "visual reconstruction"]', 'RICE visual reconstruction; not an authenticated documentary photograph.', 'field-at-1942.html', NULL);
INSERT INTO works (project_slug, program_key, series_key, series_title, author, title, status, sort_order, notes, cover_image, popup_description, kind, place, keywords, disclosure, href, published_at) VALUES ('damp-heat-index', 'rice', 'seed', 'Seed', 'RICE Editors', 'Damp Heat Index', 'sample', 1007, 'ref: RICE-VR-ARC-002', 'assets/images/archive/athens-archival-evidence.jpg', 'A prototype copy-bed composition demonstrating a future archive treatment.', 'archive', 'Athens, Georgia', '["archive", "documents", "visual reconstruction"]', 'RICE visual reconstruction; not an authenticated historical document.', 'damp-heat-index.html', NULL);
INSERT INTO works (project_slug, program_key, series_key, series_title, author, title, status, sort_order, notes, cover_image, popup_description, kind, place, keywords, disclosure, href, published_at) VALUES ('rice-rice-arc-withdrawn-001', 'rice', 'seed', 'Seed', NULL, 'Mill Ledger, 1911', 'withdrawn', 1008, NULL, NULL, 'Withdrawn synthetic ledger record retained only for audit history.', 'archive', 'Acadia Parish', '["withdrawn", "visual reconstruction"]', 'Withdrawn because its synthetic details could be mistaken for authenticated history.', NULL, NULL);
